name: Automated Tests 
on: pull_request
jobs: 
  jest:
    name: Jest Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@4

      - uses: actions/setupe-node@4
        with:
          node-version: "lts/hydrogen"
        
      - run: npm run ci

      - run: npm run test
